# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

ll_notify:
  defaults:
    notifier:
      position: bottom-right

# Dashboards
lovelace:
  mode: yaml
  dashboards:
    llnotify-dashboard:
      mode: yaml
      title: ll_notify Test Dashboard
      show_in_sidebar: true
      filename: ll_notify_dashboard.yaml

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug
